# Generated by Django 4.1.7 on 2023-03-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('ANIMAL', 'Animal'), ('FLOWER', 'Flower'), ('PEOPLE', 'People'), ('OTHER', 'Other')], default='OTHER', max_length=255)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
